### ISSUE TITLE
Properties and Assisted injection don't work together

### ISSUE THREAD

**Issue by yaitskov** [google/guice#1003]
```
    @Inject
    private int timeoutSeconds;  
    @Inject
    private HandlerFactory wsHandlerProvider;

    public void start() throws Exception {
        createInjector(new VertxModule(vertx), new GuiceWhenBinder(),
                new PropertiesContext(), new Context())
                .injectMembers(this);

public class Context extends AbstractModule {
    @Override
    protected void configure() {
        install(new FactoryModuleBuilder()
                .implement(HandlerBuffer.class, WsHandler.class)
                .build(HandlerFactory.class));
    }
}

public class PropertiesContext extends AbstractModule {
    @Override
    protected void configure() {
        Names.bindProperties(binder(), ImmutableMap.of("timeoutSeconds", "30"));
    }
}
```

Error
```
com.google.inject.ConfigurationException: Guice configuration errors:

1) Could not find a suitable constructor in java.lang.Integer. Classes must have either one (and only one) constructor annotated with @Inject or a zero-argument constructor that is not private.
  at java.lang.Integer.class(Integer.java:52)
  while locating java.lang.Integer
    for field at com.haba.Hub.timeoutSeconds(Hub.java:18)
  while locating com.haba.Hub

1 error
	at com.google.inject.internal.InjectorImpl.getMembersInjector(InjectorImpl.java:992)
	at com.google.inject.internal.InjectorImpl.getMembersInjector(InjectorImpl.java:997)
	at com.google.inject.internal.InjectorImpl.injectMembers(InjectorImpl.java:983)
	at com.haba.Hub.start(Hub.java:34)
	at io.vertx.core.AbstractVerticle.start(AbstractVerticle.java:111)
	at io.vertx.core.impl.DeploymentManager.lambda$doDeploy$159(DeploymentManager.java:429)
	at io.vertx.core.impl.ContextImpl.lambda$wrapTask$16(ContextImpl.java:335)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:358)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:357)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:112)
	at java.lang.Thread.run(Thread.java:745)
Mar 17, 2016 9:59:39 AM io.vertx.core.impl.launcher.commands.VertxIsolatedDeployer
SEVERE: Failed in deploying verticle
com.google.inject.ConfigurationException: Guice configuration errors:

1) Could not find a suitable constructor in java.lang.Integer. Classes must have either one (and only one) constructor annotated with @Inject or a zero-argument constructor that is not private.
  at java.lang.Integer.class(Integer.java:52)
  while locating java.lang.Integer
    for field at com.haba.Hub.timeoutSeconds(Hub.java:18)
  while locating com.haba.Hub

1 error
	at com.google.inject.internal.InjectorImpl.getMembersInjector(InjectorImpl.java:992)
	at com.google.inject.internal.InjectorImpl.getMembersInjector(InjectorImpl.java:997)
	at com.google.inject.internal.InjectorImpl.injectMembers(InjectorImpl.java:983)
	at com.haba.Hub.start(Hub.java:34)
	at io.vertx.core.AbstractVerticle.start(AbstractVerticle.java:111)
	at io.vertx.core.impl.DeploymentManager.lambda$doDeploy$159(DeploymentManager.java:429)
	at io.vertx.core.impl.ContextImpl.lambda$wrapTask$16(ContextImpl.java:335)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:358)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:357)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:112)
	at java.lang.Thread.run(Thread.java:745)

com.google.inject.ConfigurationException: Guice configuration errors:

1) Could not find a suitable constructor in java.lang.Integer. Classes must have either one (and only one) constructor annotated with @Inject or a zero-argument constructor that is not private.
  at java.lang.Integer.class(Integer.java:52)
  while locating java.lang.Integer
    for field at com.haba.Hub.timeoutSeconds(Hub.java:18)
  while locating com.haba.Hub

1 error
	at com.google.inject.internal.InjectorImpl.getMembersInjector(InjectorImpl.java:992)
	at com.google.inject.internal.InjectorImpl.getMembersInjector(InjectorImpl.java:997)
	at com.google.inject.internal.InjectorImpl.injectMembers(InjectorImpl.java:983)
	at com.haba.Hub.start(Hub.java:34)
	at io.vertx.core.AbstractVerticle.start(AbstractVerticle.java:111)
	at io.vertx.core.impl.DeploymentManager.lambda$doDeploy$159(DeploymentManager.java:429)
	at io.vertx.core.impl.ContextImpl.lambda$wrapTask$16(ContextImpl.java:335)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:358)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:357)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:112)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by yaitskov** [comment]
I found that annotating with primitive fields with  @Named("timeoutSeconds") helps.
Also String fields works. There is problem only with float, double, long and int.

Now the problem doesn't look serious but the stacktrace is horrible.

**Comment by sameb** [comment]
The error has nothing to do with AssistedInject.

It's failing because you're expecting injection to work based off variable names, but it doesn't. It works based on type and annotation. Property binding binds the types with the @Named("propertyName") annotation, so injecting without it doesn't work. String injection may be working because it ends up using  just-in-time binding for String, not because it's giving the right property.
