### ISSUE TITLE
guice annotation is not recognized in `injector.getInstance(`

### ISSUE THREAD

**Issue by elad2109** [google/guice#1007]
I have this code:

    @CostRequest private IRequestUrlRepository costRequestUrlRepository;

and 

    this.injector = Guice.createInjector(new MainModule());
            routingResponseShortRepository = injector.getInstance(IRoutingResponseShortRepository.class);
            costRequestUrlRepository = injector.getInstance(IRequestUrlRepository.class);

and this in my `mainModule.java`:

        bind(IRequestUrlRepository.class).annotatedWith(CostRequest.class).to(CostRequestUrlRepository.class);
        bind(IRequestUrlRepository.class).annotatedWith(RouteRequest.class).to(RoutingRequestUrlRepository.class);

but I get this run-time error:

    Exception in thread "main" com.google.inject.ConfigurationException: Guice configuration errors:
    
    1) No implementation for com.waze.routing.automation.interfaces.IRequestUrlRepository was bound.
      while locating com.waze.routing.automation.interfaces.IRequestUrlRepository
    
    1 error
    	at com.google.inject.internal.InjectorImpl.getProvider(InjectorImpl.java:1035)
    	at com.google.inject.internal.InjectorImpl.getProvider(InjectorImpl.java:994)
    	at com.google.inject.internal.InjectorImpl.getInstance(InjectorImpl.java:1044)
    	at com.waze.routing.automation.runners.parallel.costRequest.BlParallelGenerator.<init>(BlParallelGenerator.java:76)
    	at com.waze.routing.automation.runners.parallel.costRequest.BlParallelGenerator.main(BlParallelGenerator.java:44)
    Disconnected from the target VM, address: '127.0.0.1:64132', transport: 'socket'

how can i fix this?

I cannot annotate the 

     routingResponseShortRepository = injector.getInstance(@CostRequest IRoutingResponseShortRepository.class);

**Comment by mcculls** [comment]
To ask for something bound using a specific annotation:
```
injector.getInstance(Key.get(IRoutingResponseShortRepository.class, CostRequest.class));
```
BTW generally it's better to ask the injector for the main bootstrap class, using `@Inject` to declare its dependencies, rather than create the class with `new` and ask the injector for each dependency in turn.
