### ISSUE TITLE
 java.lang.NoClassDefFoundError: com.google.common.collect.ImmutableSet

### ISSUE THREAD

**Issue by gagaJay** [google/guice#1035]
Caused by java.lang.NoClassDefFoundError: com.google.common.collect.ImmutableSet

Hi, when I download and use the new guice 4.0, I got this error. 
I have looked into version 3.0 and 4.0 jar files and found that some classes including 'ImmutableSet.class' have been missing since version 4.0. The missing files were originally in 3.0 and keep thing works fine. Is there a dependency on 4.0 so that it can gets all those missing classes? Cheers

Full log:
java.lang.NoClassDefFoundError: com.google.common.collect.ImmutableSet
                                                                           at com.google.inject.util.Modules$RealOverriddenModuleBuilder.<init>(Modules.java:153)
                                                                           at com.google.inject.util.Modules$RealOverriddenModuleBuilder.<init>(Modules.java:149)
                                                                           at com.google.inject.util.Modules.override(Modules.java:81)

**Comment by mcculls** [comment]
You need to have Guava on the classpath (note Guice 4.0 was compiled against Guava 16.0.1 as in https://github.com/google/guice/tree/4.0/lib) - previously this was shaded into Guice, but since 4.0 it's now an external dependency.
