### ISSUE TITLE
Binding to mock instance of concrete class fails if real class cannot be injected

### ISSUE THREAD

**Issue by bcoughlan** [google/guice#1048]
(Tested on Guice 4.0 and 4.1.0)

Binding a concrete class to an instance of a mock implementation causes the injector to fail if the real class cannot be injected. The behaviour is not the same when using @Provides

````java
package sketchpad;

import static org.mockito.Mockito.mock;

import javax.inject.Inject;

import com.google.inject.AbstractModule;
import com.google.inject.Guice;
import com.google.inject.Provides;

public class GuiceTest {

	public static class A {
		@Inject
		B b;
	}

	public static interface B {

	}

	private static final class ToInstanceInjector extends AbstractModule {

		private <T> void bindMockitoMock(Class<T> cls) {
			bind(cls).toInstance(mock(cls));
		}

		@Override
		public void configure() {
			bindMockitoMock(A.class);
		}
	}

	private static final class ProvidesInjector extends AbstractModule {

		@Provides
		public A a() {
			return mock(A.class);
		}

		@Override
		protected void configure() {
		}
	}

	public static void main(String[] args) {
		//Fails
		Guice.createInjector(new ToInstanceInjector());
		
		//OK
		Guice.createInjector(new ProvidesInjector());
	}

}

```

```
`Exception in thread "main" com.google.inject.CreationException: Unable to create injector, see the following errors:

1) No implementation for sketchpad.GuiceTest$B was bound.
  while locating sketchpad.GuiceTest$B
    for field at sketchpad.GuiceTest$A.b(GuiceTest.java:13)
  at sketchpad.GuiceTest$ToInstanceInjector.bindMockitoMock(GuiceTest.java:25)

1 error
	at com.google.inject.internal.Errors.throwCreationExceptionIfErrorsExist(Errors.java:470)
	at com.google.inject.internal.InternalInjectorCreator.initializeStatically(InternalInjectorCreator.java:155)
	at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:107)
	at com.google.inject.Guice.createInjector(Guice.java:99)
	at com.google.inject.Guice.createInjector(Guice.java:73)
	at com.google.inject.Guice.createInjector(Guice.java:62)
	at sketchpad.GuiceTest.main(GuiceTest.java:48)
```

**Comment by tavianator** [comment]
This is intentional -- `toInstance(foo)` does an implicit `requestInjection(foo)`.  You can work around it with `toProvider(Providers.of(foo))`.
