### ISSUE TITLE
MethodInterception on class w/ @Injected private Constructor  throw "No visible constructor Exception"

### ISSUE THREAD

**Issue by GustavePate** [google/guice#1059]
Hi there,

Everything is in the title ;)

I like the [KeepConstructorHidden](https://github.com/google/guice/wiki/KeepConstructorsHidden) idea.
I like AOP too. But when I annotate a method from a class whose constructor is private but annotate as @Inject, Guice throws the Exception listed below.

However, I think that my code respects the [documented limitations for AOP](https://github.com/google/guice/wiki/AOP#limitations).

```
com.google.inject.CreationException: Unable to create injector, see the following errors:

1) Unable to method intercept: play.ground.annotation.guiceaop.objects.AnnotatedObject
  at play.ground.annotation.guiceaop.AOPTest$ThisTestModule.configure(AOPTest.java:37)

1 error
	at com.google.inject.internal.Errors.throwCreationExceptionIfErrorsExist(Errors.java:466)
	at com.google.inject.internal.InternalInjectorCreator.initializeStatically(InternalInjectorCreator.java:155)
	at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:107)
	at com.google.inject.Guice.createInjector(Guice.java:96)
	at com.google.inject.Guice.createInjector(Guice.java:73)
	at com.google.inject.Guice.createInjector(Guice.java:62)
	at play.ground.annotation.guiceaop.AOPTest.doit(AOPTest.java:44)
	[...]
Caused by: java.lang.IllegalArgumentException: No visible constructors in class play.ground.annotation.guiceaop.objects.AnnotatedObject
	at com.google.inject.internal.cglib.proxy.$Enhancer.filterConstructors(Enhancer.java:531)
       [...]
```
Here is a sample code to reproduce this:

My AnnotatedObject

```
public class AnnotatedObject {

	static final Logger LOG = LoggerFactory.getLogger(MyMethodInterceptor.class);

	@Inject
	@Named("conf")
	private Config conf;

	@Inject
	private AnnotatedObject() {

	}

	@MyAnnotation
	public void dosomething() {
		LOG.info("do something here...");
	}

}

```

My Interceptor

```
public class MyMethodInterceptor implements MethodInterceptor {

	static final Logger LOG = LoggerFactory.getLogger(MyMethodInterceptor.class);

	@Inject
	@Named("conf")
	private Config conf;

	public Object invoke(final MethodInvocation invocation) throws Throwable {
		Object res = null;

		LOG.info("hello");
		res = invocation.proceed();
		LOG.info("world");

		return res;

	}

}

```

The associated unit test 

```
public class AOPTest {

	static final Logger LOG = LoggerFactory.getLogger(AOPTest.class);

	public class ThisTestModule extends AbstractModule {

		protected void configure() {

			// Something real to inject in other objects
			Config conf = ConfigFactory.load("application");
			bind(Config.class).annotatedWith(Names.named("conf")).toInstance(conf);

			// Annotation / Interceptor management
			MyMethodInterceptor interceptor = new MyMethodInterceptor();
			requestInjection(interceptor);
			bindInterceptor(Matchers.any(), Matchers.annotatedWith(MyAnnotation.class), interceptor);

			// My test object binding
			bind(AnnotatedObject.class);
		}
	}

	@Test
	public void doit() {

		Injector injector = Guice.createInjector(new ThisTestModule());

		// Injection Test
		AnnotatedObject test = injector.getInstance(AnnotatedObject.class);

		test.dosomething();

	}

}

```

All the code needed to reproduce: [guiceaop.zip](https://github.com/google/guice/files/561454/guiceaop.zip)

Tested with Guice 4.0 and Guice 4.1.0 with oracle java 1.8.0.45.

Maybe I'm doing something wrong or maybe the documentation should be fixed somehow.

Let me know,

Thanks in advance

**Comment by mcculls** [comment]
One of the limitations in the above link is:

> Methods must be public, package-private or protected

This includes the constructor, which must also be public, package-private or protected.

The reason for this limitation is because Guice's AOP works by creating a subclass that applies interceptors by overriding methods. If you have a private constructor then your class cannot be subclassed.
