### ISSUE TITLE
memory leak problems

### ISSUE THREAD

**Issue by cikeGit** [google/guice#1063]
I use Guice in my project .  it  alway crash and  show PermGen space when I re-delpoy(or  hot deploy) on  Jetty or  Tomcat .  does any solutions? dears

**Comment by cikeGit** [comment]
# Error Log as following:
java.lang.OutOfMemoryError: PermGen space
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:800)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at org.eclipse.jetty.webapp.WebAppClassLoader.loadClass(WebAppClassLoader.java:421)
	at org.eclipse.jetty.webapp.WebAppClassLoader.loadClass(WebAppClassLoader.java:383)
	at org.apache.velocity.runtime.parser.Parser.<init>(Parser.java:3097)
	at org.apache.velocity.runtime.parser.Parser.<init>(Parser.java:55)
	at org.apache.velocity.runtime.RuntimeInstance.createNewParser(RuntimeInstance.java:694)
	at org.apache.velocity.runtime.RuntimeInstance.initializeParserPool(RuntimeInstance.java:681)
	at org.apache.velocity.runtime.RuntimeInstance.init(RuntimeInstance.java:229)
	at org.apache.velocity.runtime.RuntimeInstance.init(RuntimeInstance.java:461)
	at org.apache.velocity.runtime.RuntimeSingleton.init(RuntimeSingleton.java:208)
	at org.apache.velocity.app.Velocity.init(Velocity.java:106)
	at com.nuskin.core.VelocityInitListener.contextInitialized(VelocityInitListener.java:32)
	at org.eclipse.jetty.server.handler.ContextHandler.callContextInitialized(ContextHandler.java:782)
	at org.eclipse.jetty.servlet.ServletContextHandler.callContextInitialized(ServletContextHandler.java:424)
	at org.eclipse.jetty.server.handler.ContextHandler.startContext(ContextHandler.java:774)
	at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:249)
	at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1242)
	at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:717)
	at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:494)
	at org.mortbay.jetty.plugin.JettyWebAppContext.doStart(JettyWebAppContext.java:298)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:64)
	at org.mortbay.jetty.plugin.JettyRunMojo.restartWebApp(JettyRunMojo.java:435)
	at org.mortbay.jetty.plugin.JettyRunMojo$1.filesChanged(JettyRunMojo.java:394)
	at org.eclipse.jetty.util.Scanner.reportBulkChanges(Scanner.java:691)

**Comment by sblommers** [comment]
I don't think your problem is related to Guice. Consider creating a reproducible Test case for your problem.
