### ISSUE TITLE
Guice hides failures in static initialization

### ISSUE THREAD

**Issue by Groostav** [google/guice#1064]
When using guice to resolve an object I'm getting a `ClassDefNotFoundError`, but when trying to access a static field (created by a dependants `clinit`) I get a much more specific exception inside a static initializer. It logically follows that guice is hiding static initializer errors. 

I _suspect_ this has to do with non-ideal treatment of `getClass()` or `Class.forName()`, for a class whose static initializer fails. The result is a `NoClassDefFoundError` which gets propagated, erasing the initial information about the failed static initializer.

I'm hoping thats enough information to go on as reducing this to an SSCCE will likely be some leg work for me.

I'm on `guice:4.1.0`. 

Note I'm also using a couple of `kotlin` files with `companion object { @JvmField /*a compiler directive*/ val whatever: Whatever = ...`'s here, so kotlin might be partially (completely?) to blame here.

**stack trace when calling dependency chain directly**

```
java.lang.ExceptionInInitializerError
	at com.empowerops.front_end.bootstrapping.OASISBootstrapper.startOASIS(OASISBootstrapper.java:185)
	at com.empowerops.front_end.bootstrapping.OASISBootstrapper.main(OASISBootstrapper.java:146)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)
Caused by: com.empowerops.common.ModelUpdaterService$RegistrationException: the controller [our specific exception --that should be preserved by guice!!]
	at com.empowerops.common.ModelUpdaterService.assertHasNewSubscribers(ModelUpdaterService.java:541)
	at com.empowerops.common.ModelUpdaterService.registerForModelPush(ModelUpdaterService.java:221)
```

**stack trace when called through guice:**

```
1) Error in custom provider, java.lang.NoSuchMethodError: com.empowerops.algorithms.OptimizationExecutor: method <init>()V not found
  at com.empowerops.front_end.bootstrapping.OASISBootstrapper$OASISModule.getOptimizerService(OASISBootstrapper.java:367)
  at com.empowerops.front_end.bootstrapping.OASISBootstrapper$OASISModule.getOptimizerService(OASISBootstrapper.java:367)
  while locating [other things]
Caused by: java.lang.NoSuchMethodError: com.empowerops.algorithms.OptimizationExecutor: method <init>()V not found
	at com.empowerops.algorithms.OptimizationExecutor$Null.<init>(OptimizationExecutor.kt:364)
	at com.empowerops.algorithms.OptimizationExecutor.<clinit>(OptimizationExecutor.kt:395)
	at com.empowerops.algorithms.OptimizerService.<init>(OptimizerService.java:79)
	at com.empowerops.algorithms.OptimizerService$Null.<init>(OptimizerService.java:409)
	at com.empowerops.algorithms.OptimizerService.<clinit>(OptimizerService.java:53)
	at com.empowerops.algorithms.OptimizerService$$FastClassByGuice$$f709d17e.newInstance(<generated>)
	at com.google.inject.internal.DefaultConstructionProxyFactory$FastClassProxy.newInstance(DefaultConstructionProxyFactory.java:89)
	at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:111)
	at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:90)
	at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:268)
	at com.google.inject.internal.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:46)
	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1092)
	at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
	at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:194)
	at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:41)
	at com.google.inject.internal.InjectorImpl$2$1.call(InjectorImpl.java:1019)
	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1085)
	at com.google.inject.internal.InjectorImpl$2.get(InjectorImpl.java:1015)
	at com.google.inject.internal.InjectorImpl.getInstance(InjectorImpl.java:1054)
	at com.empowerops.algorithms.OptimizationBootstrapper.makeOptimizerService(OptimizationBootstrapper.java:74)
	at com.empowerops.front_end.bootstrapping.OASISBootstrapper$OASISModule.getOptimizerService(OASISBootstrapper.java:367)
	at com.empowerops.front_end.bootstrapping.OASISBootstrapper$OASISModule$$FastClassByGuice$$21dcd62a.invoke(<generated>)
	at com.google.inject.internal.ProviderMethod$FastClassProviderMethod.doProvision(ProviderMethod.java:264)
	at com.google.inject.internal.ProviderMethod$Factory.provision(ProviderMethod.java:401)
	at com.google.inject.internal.ProviderMethod$Factory.get(ProviderMethod.java:376)
	at com.google.inject.internal.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:46)
	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1092)
	at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
	at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:194)
	at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:41)
	at com.google.inject.internal.SingleParameterInjector.inject(SingleParameterInjector.java:38)
	at com.google.inject.internal.SingleParameterInjector.getAll(SingleParameterInjector.java:62)
	at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:110)
	at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:90)
	at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:268)
	at com.google.inject.internal.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:46)
	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1092)
	at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
	at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:194)
	at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:41)
	at com.google.inject.internal.SingleParameterInjector.inject(SingleParameterInjector.java:38)
	at com.google.inject.internal.SingleParameterInjector.getAll(SingleParameterInjector.java:62)
	at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:110)
	at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:90)
	at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:268)
	at com.google.inject.internal.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:46)
	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1092)
	at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
	at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:194)
	at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:41)
	at com.google.inject.internal.SingleParameterInjector.inject(SingleParameterInjector.java:38)
	at com.google.inject.internal.SingleParameterInjector.getAll(SingleParameterInjector.java:62)
	at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:110)
	at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:90)
	at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:268)
	at com.google.inject.internal.SingleFieldInjector.inject(SingleFieldInjector.java:54)
	at com.google.inject.internal.MembersInjectorImpl.injectMembers(MembersInjectorImpl.java:132)
	at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:120)
	at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:90)
	at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:268)
	at com.google.inject.internal.InjectorImpl$2$1.call(InjectorImpl.java:1019)
	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1085)
	at com.google.inject.internal.InjectorImpl$2.get(InjectorImpl.java:1015)
	at com.google.inject.internal.InjectorImpl.getInstance(InjectorImpl.java:1054)
	at com.empowerops.front_end.bootstrapping.OASISBootstrapper.startOASIS(OASISBootstrapper.java:192)
	at com.empowerops.front_end.bootstrapping.OASISBootstrapper.main(OASISBootstrapper.java:146)

2) Error in custom provider, java.lang.NoClassDefFoundError: Could not initialize class com.empowerops.algorithms.OptimizerService
  at com.empowerops.front_end.bootstrapping.OASISBootstrapper$OASISModule.getOptimizerService(OASISBootstrapper.java:367)
  at com.empowerops.front_end.bootstrapping.OASISBootstrapper$OASISModule.getOptimizerService(OASISBootstrapper.java:367)
  while locating [other things]
Caused by: java.lang.NoClassDefFoundError: Could not initialize class com.empowerops.algorithms.OptimizerService
	at com.empowerops.algorithms.OptimizerService$$FastClassByGuice$$f709d17e.newInstance(<generated>)
	at com.google.inject.internal.DefaultConstructionProxyFactory$FastClassProxy.newInstance(DefaultConstructionProxyFactory.java:89)
	at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:111)
  at [the same trace as above]
```

**Comment by Groostav** [comment]
I'm sorry this is actually an error in the kotlin compiler:

https://youtrack.jetbrains.com/issue/KT-14955

Sorry for wasting your time!
