### ISSUE TITLE
Unexpected interceptor behavior

### ISSUE THREAD

**Issue by WowMuchName** [google/guice#1094]
We had a problem where Guice would not apply method-interceptors, neither the ones that come with shiro nor the ones we created outselfs. An nearly identical setup works in our JavaFX apps.

After a lot of tinkering this is what we found: 

**Working version**:
https://gist.github.com/WowMuchName/49736aef6a0de919a3491ac6517b2da3#file-bootstrap_working-java

_Output (Part):_
[...]
@X() (xxx.BootStrap$X:ALL in 662a0cc6)
java.io.IOException
	at xxx.BootStrap$X.<init>(BootStrap.java:40)
	at xxx.BootStrap$X$$**EnhancerByGuice**$$5856a3cb.<init>(<generated>)
[...]
Intercepted[Test]
_Endofoutput_

**None-working version**:
https://gist.github.com/WowMuchName/49736aef6a0de919a3491ac6517b2da3#file-bootstrap_not_working-java

The only difference is that instead of

`Guice.createInjector(allMyModules)`

we do

`Guice.createInjector(modulesPart1).createChildInjector(modulesPart2)`

Ouput:

@X() (xxx.BootStrap$X:ALL in 67ca9a88)
Test
java.io.IOException
	at xxx.BootStrap$X.<init>(BootStrap.java:40)
	at xxx.BootStrap$X$$**FastClassByGuice**$$f986fcc8.newInstance(<generated>)

As can be seen injection **does** work. What doesn't work is interception. Guice creates a Fast not an Enhanced class.

Are we missing something here? So far we are unable to reproduce this outside the servlet container. If this for some reason is a none-fixable issue or even desired it should be documented. Our expectation was that Guice would work in the Servlet-Container as it does in a standalone app which doesn't seem to be the case.

**Comment by WowMuchName** [comment]
Okay, it turns out we can reproduce this outside the servlet-container after all. I'm closing this for now since we can't rule out a problem on our end at the moment.

**Comment by WowMuchName** [comment]
The issue is not with the servlet module or the servlet container at all. It was just a coincidence that we encountered the issue there for the first time. I updated the title to reflect that.

`Guice.createInjector(interceptorModule).createChildInjector(otherModule)`

is fine

`Guice.createInjector(otherModule).createChildInjector(interceptorModule)`

is **not**. If we get an instance _injection_ works, _intercepetion_ does **not**


Our assumption is as follows, since we get a just-in-time binding guice initializes that in the root-injector, even if we request it from the child-injector. The root-injector is unaware of the interceptorModule and doesn't bind any interceptors.

It would be helpfull if a dev could verify whether that assumption is correct.

In createChildInjectors javadoc it says:

"Just-in-time bindings created for child injectors will be created in an ancestor injector whenever **possible**"

However if the child-injector has interceptors that are usable on the class to be instantiated, guice should realize that this is not possible and either create them in the child-injector or throw an excpetion. In our opinion Guice does not act in accordance with its java-doc in this situation. This should be either fixed or at least documented in the javadoc. It took as over a week to even understand where the problem is.

**Comment by WowMuchName** [comment]
Our workaround for now is to create the injector with one call.

However we use our own wrapper around Guice. We create a "first level injector" then carry out a search over all META-INF folders, similar to what the java-service loader does. The modules discovered in that fashion are created with the first-level-injector and are used to create the second-level-injector which is passed back to the app. Since it seems we can't have multiple levels we can't load the modules via injector anymore and had to revert to instancing them using reflection. This works for now but is not the result we were hoping for.

If this will be accepted as a bug we are willing to contribute to getting it fixed.

**Comment by dimo414** [comment]
There are a number of conceptual issues with child injectors, and this seems like one such case. For your case you might consider simply constructing a *new* injector that takes all the modules (from the original injector and from the newly discovered modules) in one go. You might even find there are bindings in the first injector that the second injector doesn't really need.

If that doesn't work for you proposing a fix would be welcome, but it would need to take into account the existing behavior in order to be backwards-compatible.
