### ISSUE TITLE
Guice provision errors

### ISSUE THREAD

**Issue by Kritiii** [google/guice#1107]
i imported [this project](https://github.com/feribg/audiogetter/tree/master/audiogetter/src/main/java/com/github/feribg/audiogetter) from github. but when i run this project, app crashes.
This is the logcat error.

    FATAL EXCEPTION: main
    Process: com.github.feribg.audiogetter, PID: 14007
    com.google.inject.ProvisionException: Guice provision errors:

    1) Error injecting constructor, java.lang.Exception: The output folder: /storage/emulated/0/Music/samples is not writable
       at com.github.feribg.audiogetter.controllers.SourceController.<init>(Unknown Source)
       at com.github.feribg.audiogetter.controllers.SourceController.class(Unknown Source)
     while locating com.github.feribg.audiogetter.controllers.SourceController
       for field at com.github.feribg.audiogetter.ui.fragments.SearchResultsBaseFragment.sourceController(Unknown Source)
     while locating com.github.feribg.audiogetter.ui.fragments.SoundcloudSearchResultsFragment

    1 error
       at com.google.inject.internal.Errors.throwProvisionExceptionIfErrorsExist(Errors.java:451)
       at com.google.inject.internal.MembersInjectorImpl.injectMembers(MembersInjectorImpl.java:65)
       at com.google.inject.internal.InjectorImpl.injectMembers(InjectorImpl.java:944)
       at roboguice.inject.ContextScopedRoboInjector.injectMembersWithoutViews(ContextScopedRoboInjector.java:243)
       at roboguice.fragment.RoboListFragment.onCreate(RoboListFragment.java:13)
       at android.support.v4.app.Fragment.performCreate(Fragment.java:2075)
       at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1060)
       at android.support.v4.app.BackStackRecord.setLastIn(BackStackRecord.java:838)
       at android.support.v4.app.BackStackRecord.calculateFragments(BackStackRecord.java:861)
       at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:719)
       at android.support.v4.app.FragmentManagerImpl.execSingleAction(FragmentManager.java:1643)
       at android.support.v4.app.BackStackRecord.commitNowAllowingStateLoss(BackStackRecord.java:679)
       at android.support.v4.app.FragmentPagerAdapter.finishUpdate(FragmentPagerAdapter.java:143)
       at android.support.v4.view.ViewPager.populate(ViewPager.java:1272)
       at android.support.v4.view.ViewPager.populate(ViewPager.java:1120)
       at android.support.v4.view.ViewPager.onMeasure(ViewPager.java:1646)
       at android.view.View.measure(View.java:17547)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5535)
       at android.widget.FrameLayout.onMeasure(FrameLayout.java:436)
       at android.view.View.measure(View.java:17547)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5535)
       at com.android.internal.widget.ActionBarOverlayLayout.onMeasure(ActionBarOverlayLayout.java:447)
       at android.view.View.measure(View.java:17547)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5535)
       at android.widget.FrameLayout.onMeasure(FrameLayout.java:436)
       at com.android.internal.policy.impl.PhoneWindow$DecorView.onMeasure(PhoneWindow.java:2615)
       at android.view.View.measure(View.java:17547)
       at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2015)
       at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1173)
       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1379)
       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1061)
       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5885)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:767)
       at android.view.Choreographer.doCallbacks(Choreographer.java:580)
       at android.view.Choreographer.doFrame(Choreographer.java:550)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:753)
       at android.os.Handler.handleCallback(Handler.java:739)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:135)
       at android.app.ActivityThread.main(ActivityThread.java:5254)
       at java.lang.reflect.Method.invoke(Native Method)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
    Caused by: java.lang.Exception: The output folder: /storage/emulated/0/Music/samples is not writable
    at com.github.feribg.audiogetter.controllers.SourceController.<in

**Comment by lukegb** [comment]
The output folder: /storage/emulated/0/Music/samples is not writable

**Comment by dimo414** [comment]
Guice injection is designed to fail this way (with a provision error) if it cannot instantiate a binding. If you're having a problem with the geribg/audiogetter project that's where you should start, not Guice. Also, doing [I/O during Guice provisioning](https://github.com/google/guice/wiki/BeCarefulAboutIoInProviders) is discouraged, so I'd try to find another way to do this operation after the Guice injector is created.
