### ISSUE TITLE
ComputationException due to StackOverflowError during injection is hard to track down

### ISSUE THREAD

**Issue by 1605200517** [google/guice#1119]
In the issue [guice/#681](https://github.com/google/guice/issues/681) it was suggested that in some rare case in a complex context Guice's ComputationException would be very hard to debug.

This scenario seems to have been dismissed as too far from reality. However, we experience now exactly the modeled situation:

- complex project context with many dependencies
- ComputationException is not possible to track down
- provided `ProvisionListener` example in the linked issue does not produce desired output, maybe I am missing something
- Guice Grapher integration does not work from scratch neither, however I am not sure how exactly this would help to analyze the problem.

```
Exception in thread "main" com.google.inject.internal.util.$ComputationException: java.lang.ArrayIndexOutOfBoundsExcepti
        at com.google.inject.internal.util.$MapMaker$StrategyImpl.compute(MapMaker.java:553)
        at com.google.inject.internal.util.$MapMaker$StrategyImpl.compute(MapMaker.java:419)
        at com.google.inject.internal.util.$CustomConcurrentHashMap$ComputingImpl.get(CustomConcurrentHashMap.java:2041)
        at com.google.inject.internal.util.$StackTraceElements.forMember(StackTraceElements.java:53)
        at com.google.inject.internal.Errors.formatSource(Errors.java:690)
        at com.google.inject.internal.Errors.formatInjectionPoint(Errors.java:720)
        at com.google.inject.internal.Errors.formatSource(Errors.java:684)
        at com.google.inject.internal.Errors.format(Errors.java:555)
        at com.google.inject.ProvisionException.getMessage(ProvisionException.java:59)
        at my.custom.spark.app.main.Main.main(Main.java:68)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.spark.deploy.SparkSubmit$.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:731)
        at org.apache.spark.deploy.SparkSubmit$.doRunMain$1(SparkSubmit.scala:181)
        at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:206)
        at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:121)
        at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
Caused by: java.lang.ArrayIndexOutOfBoundsException: 43168
        at com.google.inject.internal.asm.$ClassReader.<init>(Unknown Source)
        at com.google.inject.internal.asm.$ClassReader.<init>(Unknown Source)
        at com.google.inject.internal.asm.$ClassReader.<init>(Unknown Source)
        at com.google.inject.internal.util.$LineNumbers.<init>(LineNumbers.java:62)
        at com.google.inject.internal.util.$StackTraceElements$1.apply(StackTraceElements.java:36)
        at com.google.inject.internal.util.$StackTraceElements$1.apply(StackTraceElements.java:33)
        **at com.google.inject.internal.util.$MapMaker$StrategyImpl.compute(MapMaker.java:549)**
        ... 18 more
```

**Comment by 1605200517** [comment]
See also https://github.com/google/guava/issues/2878

**Comment by dimo414** [comment]
I would start by trying to [reproduce the issue with a smaller example](https://stackoverflow.com/help/mcve). Without any code it's hard to identify an appropriate resolution.

**Comment by 1605200517** [comment]
@dimo414  the trouble we have here that this exception appears to be more or less generic in more complex setups. Probably a reduced example would go along the lines of guice/#681: "..it's relatively easy to construct dependency chains that overflow the available stack. In my testing I was able to do it with a chain of length seven"

**Comment by viep** [comment]
Any resolution for this?
