### ISSUE TITLE
GraphvizGrapher renderEdge throws NPE

### ISSUE THREAD

**Issue by r0b0ji** [google/guice#1135]
I wanted to create a visualization of dependency for my guice  bindings. I use the GraphvizGrapher to do that. I followed the another [SO question](https://stackoverflow.com/questions/9301007/is-there-any-way-to-get-guice-grapher-to-work) asked on this. But when I run that, I get NPE in GraphvizGrapher.  

I am using guice 4.0. Below is the trace. I don't see much questions  or information on Grapher and it never worked for me. Wondering if  anyone uses it.    

Exception in thread "main" java.lang.NullPointerException 
at  com.google.inject.grapher.graphviz.GraphvizGrapher.renderEdge(GraphvizGrapher.java:172)     at com.google.inject.grapher.graphviz.GraphvizGrapher.postProcess(GraphvizGrapher.java:85) 
at com.google.inject.grapher.AbstractInjectorGrapher.graph(AbstractInjectorGrapher.java:112)  
at com.google.inject.grapher.AbstractInjectorGrapher.graph(AbstractInjectorGrapher.java:102)  
at com.amazon.imsreconciliation.modules.ModuleGraph.graph(ModuleGraph.java:24)  
at com.amazon.imsreconciliation.modules.ModuleGraph.main(ModuleGraph.java:44)

**Comment by r0b0ji** [comment]
Finally after lots of debugging found the root cause.

For ProviderInstanceBinding and InstanceBinding, DefaultEdgeCreator creates one edge from Type->Instance and then also adds all dependency edges. [In newDependencyEdges](https://github.com/google/guice/blob/master/extensions/grapher/src/com/google/inject/grapher/DefaultEdgeCreator.java#L69), the `to` is an interface node with `dependency.getKey()`

But DefaultNodeCreator never created this node. [DefaulNodeCreator only creates an interface node and instance node, not dependent nodes.](https://github.com/google/guice/blob/master/extensions/grapher/src/com/google/inject/grapher/DefaultNodeCreator.java#L114-L128)
So, when in GraphvizGrapher, [it tries to render that edge](https://github.com/google/guice/blob/master/extensions/grapher/src/com/google/inject/grapher/graphviz/GraphvizGrapher.java#L178), `nodes.get(edge.getHeadNodeId())`, it doesn't find any node and so method call `getIdentifier()` throws NPE.

**Comment by r0b0ji** [comment]
A simple code to reproduce this issue


```
public class TopLevelClass {
    private final String someStringValue;
    public TopLevelClass(String stringValue) {
        this.someStringValue = stringValue;
    }
}
```

```
public class MainModule extends AbstractModule {
    @Provides
    TopLevelClass provideTop(@Named("some_string_identifier")  String value) {
        return new TopLevelClass(value);
    }
}
```

```
public class TestMain {
    public static void main() throws IOException {
        Injector injector = Guice.createInjector(new MainModule());
        graph(injector);
    }

    public static void graph(Injector injector) throws IOException {
         PrintWriter writer = new PrintWriter(new File("some_file.dot"), "UTF-8");

        Injector graphInjector = Guice.createInjector(new GraphvizModule());
        GraphvizGrapher grapher = graphInjector.getInstance(GraphvizGrapher.class);
       grapher.setOut(writer);
       grapher.setRankDir("TB");
       grapher.graph(injector, Collections.singleton(Key.get(TopLevelClass.class)));
   }
}
```

**Comment by aj09ay** [comment]
Have you figured out a solution for this ?
