### ISSUE TITLE
checkNotNull Error.

### ISSUE THREAD

**Issue by nakhanha** [google/guice#1210]
```
2018-10-08T19:13:17.108Z        ERROR   main    com.facebook.presto.server.PrestoServer com.google.inject.internal.Errors.checkNotNull(Ljava/lang/Object;Ljava/lang/String;)Ljava/lang/Object;
java.lang.NoSuchMethodError: com.google.inject.internal.Errors.checkNotNull(Ljava/lang/Object;Ljava/lang/String;)Ljava/lang/Object;
        at com.google.inject.internal.RealMultibinder.<init>(RealMultibinder.java:88)
        at com.google.inject.internal.RealMultibinder.newRealSetBinder(RealMultibinder.java:56)
        at com.google.inject.multibindings.Multibinder.newSetBinder(Multibinder.java:136)
        at com.google.inject.multibindings.Multibinder.newSetBinder(Multibinder.java:99)
        at io.airlift.event.client.EventModule.configure(EventModule.java:31)
        at com.google.inject.spi.Elements$RecordingBinder.install(Elements.java:223)
        at com.google.inject.spi.Elements.getElements(Elements.java:101)
        at com.google.inject.spi.Elements.getElements(Elements.java:92)
        at io.airlift.configuration.ConfigurationFactory.registerConfigurationClasses(ConfigurationFactory.java:164)
        at io.airlift.bootstrap.Bootstrap.initialize(Bootstrap.java:199)
        at com.facebook.presto.hive.HiveConnectorFactory.create(HiveConnectorFactory.java:115)
        at com.facebook.presto.connector.ConnectorManager.createConnector(ConnectorManager.java:319)
        at com.facebook.presto.connector.ConnectorManager.addCatalogConnector(ConnectorManager.java:195)
        at com.facebook.presto.connector.ConnectorManager.createConnection(ConnectorManager.java:187)
        at com.facebook.presto.connector.ConnectorManager.createConnection(ConnectorManager.java:173)
        at com.facebook.presto.metadata.StaticCatalogStore.loadCatalog(StaticCatalogStore.java:96)
        at com.facebook.presto.metadata.StaticCatalogStore.loadCatalogs(StaticCatalogStore.java:74)
        at com.facebook.presto.server.PrestoServer.run(PrestoServer.java:119)
        at com.facebook.presto.server.PrestoServer.main(PrestoServer.java:67)
```

I added guice and I am facing the following error.  Without guice it was working fine.

Please help.

**Comment by dimo414** [comment]
My guess is `io.airlift.event.client.EventModule.configure()` is doing something wrong, or you're passing something wrong into it (or wherever earlier in the stack trace there's code you control).

Note that GitHub issue trackers are not a support channel - they are for reporting bugs and filing feature requests. There's nothing in that stack trace that suggests Guice is doing anything wrong. Look into how you're using it.

**Comment by johnedmonds** [comment]
We had this issue. It was because we had another jar containing classes from a really old version of Guice (sisu-guice). So there were 2 Guice jars on the classpath.
