### ISSUE TITLE
spark 2.4.0 guice 4.x ERROR

### ISSUE THREAD

**Issue by sungbinyoon** [google/guice#1239]
In spark 2.3.0 scala 2.11.8, I was using the version 4.1.0 well. Now I am testing the upgrade of spark 2.4.0 scala 2.12.4 version. 
During the test, the following error occurred in the guice: Error seems to occur during the `Guice.createInject().getInstance` process. I applied the latest version of 4.2.2, and the same error message was found.
```
Exception in thread "main" java.lang.ExceptionInInitializerError
	at ai.company.baloo.env.guice.InTest$.main(InTest.scala:23)
	at ai.company.baloo.env.guice.InTest.main(InTest.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.spark.deploy.JavaMainApplication.start(SparkApplication.scala:52)
	at org.apache.spark.deploy.SparkSubmit.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:849)
	at org.apache.spark.deploy.SparkSubmit.doRunMain$1(SparkSubmit.scala:167)
	at org.apache.spark.deploy.SparkSubmit.submit(SparkSubmit.scala:195)
	at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:86)
	at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:924)
	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:933)
	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
Caused by: com.google.inject.internal.util.$ComputationException: java.lang.ArrayIndexOutOfBoundsException: 86533
	at com.google.inject.internal.util.$MapMaker$StrategyImpl.compute(MapMaker.java:553)
	at com.google.inject.internal.util.$MapMaker$StrategyImpl.compute(MapMaker.java:419)
	at com.google.inject.internal.util.$CustomConcurrentHashMap$ComputingImpl.get(CustomConcurrentHashMap.java:2041)
	at com.google.inject.internal.util.$StackTraceElements.forMember(StackTraceElements.java:53)
	at com.google.inject.internal.Errors.formatInjectionPoint(Errors.java:716)
	at com.google.inject.internal.Errors.formatSource(Errors.java:678)
	at com.google.inject.internal.Errors.format(Errors.java:555)
	at com.google.inject.ProvisionException.getMessage(ProvisionException.java:59)
	at java.lang.Throwable.getLocalizedMessage(Throwable.java:391)
	at java.lang.Throwable.toString(Throwable.java:480)
	at java.lang.String.valueOf(String.java:2994)
	at java.io.PrintStream.println(PrintStream.java:821)
	at java.lang.Throwable$WrappedPrintStream.println(Throwable.java:748)
	at java.lang.Throwable.printStackTrace(Throwable.java:655)
	at java.lang.Throwable.printStackTrace(Throwable.java:643)
	at java.lang.Throwable.printStackTrace(Throwable.java:634)
	at ai.company.baloo.env.guice.InjectM$.liftedTree1$1(InTest.scala:47)
	at ai.company.baloo.env.guice.InjectM$.<init>(InTest.scala:44)
	at ai.company.baloo.env.guice.InjectM$.<clinit>(InTest.scala)
	... 14 more
Caused by: java.lang.ArrayIndexOutOfBoundsException: 86533
	at com.google.inject.internal.asm.$ClassReader.<init>(Unknown Source)
	at com.google.inject.internal.asm.$ClassReader.<init>(Unknown Source)
	at com.google.inject.internal.asm.$ClassReader.<init>(Unknown Source)
	at com.google.inject.internal.util.$LineNumbers.<init>(LineNumbers.java:62)
	at com.google.inject.internal.util.$StackTraceElements$1.apply(StackTraceElements.java:36)
	at com.google.inject.internal.util.$StackTraceElements$1.apply(StackTraceElements.java:33)
	at com.google.inject.internal.util.$MapMaker$StrategyImpl.compute(MapMaker.java:549)
	... 32 more
```

**Comment by kalinows** [comment]
Observed a similar ArrayIndexOutOfBoundsException in Guice 3.0. The exception is being thrown during execution of the getMessage() method:

    com.google.inject.internal.util.$ComputationException: java.lang.ArrayIndexOutOfBoundsException: 1612
         at com.google.inject.internal.util.$MapMaker$StrategyImpl.compute(MapMaker.java:553)
         at com.google.inject.internal.util.$MapMaker$StrategyImpl.compute(MapMaker.java:419)
         at com.google.inject.internal.util.$CustomConcurrentHashMap$ComputingImpl.get(CustomConcurrentHashMap.java:2041)
         at com.google.inject.internal.util.$StackTraceElements.forMember(StackTraceElements.java:53)
         at com.google.inject.internal.Errors.formatInjectionPoint(Errors.java:716)
         at com.google.inject.internal.Errors.formatSource(Errors.java:678)
         at com.google.inject.internal.Errors.format(Errors.java:555)
         at com.google.inject.ProvisionException.getMessage(ProvisionException.java:59)

**Comment by winfriedgerlach** [comment]
@sungbin07 @cushon @eamonnmcmanus since this issues concerns the outdated Guice version 4.x and has been inactive for years, can this issue be closed?
