### ISSUE TITLE
Modules override with private modules fails when there is no binding to override

### ISSUE THREAD

**Issue by fusr** [google/guice#1259]
I'm having issues with overriding default binding and private modules. It looks like when a module overriding bindings has nothing to override it fails.

Is this expected behavior?

This works

```
    val injector = Guice.createInjector(Modules.override(
            object : KotlinPrivateModule() {
                override fun configure() {
                    bind<MyService>().to<DefaultMyService>().`in`<Singleton>()
                    expose<MyService>()
                }
            }
    ).with(
            object : KotlinPrivateModule() {
                override fun configure() {
                    bind<MyService>().to<MyServiceImpl>().`in`<Singleton>()
                    expose<MyService>()
                }
            }
    ))
    val myService = injector.getInstance<MyService>()
    myService.doWork()
```

This works 

```
    val injector = Guice.createInjector(Modules.override(
            object : KotlinPrivateModule() {
                override fun configure() {
                    bind<MyDatabase>().to<DefaultMyDatabase>().`in`<Singleton>()
                    expose<MyDatabase>()
                    bind<MyService>().to<DefaultMyService>().`in`<Singleton>()
                    expose<MyService>()
                }
            }
    ).with(
            object : KotlinPrivateModule() {
                override fun configure() {
                    bind<MyService>().to<MyServiceImpl>().`in`<Singleton>()
                    expose<MyService>()
                }
            }
    ))
    val myService = injector.getInstance<MyService>()
    val myDatabase = injector.getInstance<MyDatabase>()
    myService.doWork()
    myDatabase.doStuff()
```

This works 

```
    val injector = Guice.createInjector(Modules.override(
            object : KotlinPrivateModule() {
                override fun configure() {
                    bind<MyDatabase>().to<DefaultMyDatabase>().`in`<Singleton>()
                    expose<MyDatabase>()
                    bind<MyService>().to<DefaultMyService>().`in`<Singleton>()
                    expose<MyService>()
                }
            }
    ).with(
            object : KotlinPrivateModule() {
                override fun configure() {
                    bind<MyDatabase>().to<MyDatabaseImpl>().`in`<Singleton>()
                    expose<MyDatabase>()
                    bind<MyService>().to<MyServiceImpl>().`in`<Singleton>()
                    expose<MyService>()
                }
            }
    ))
    val myService = injector.getInstance<MyService>()
    val myDatabase = injector.getInstance<MyDatabase>()
    myService.doWork()
    myDatabase.doStuff()
```

But this does not

```
    val injector = Guice.createInjector(Modules.override(
            object : KotlinPrivateModule() {
                override fun configure() {
                    bind<MyService>().to<DefaultMyService>().`in`<Singleton>()
                    expose<MyService>()
                }
            }
    ).with(
            object : KotlinPrivateModule() {
                override fun configure() {
                    bind<MyDatabase>().to<MyDatabaseImpl>().`in`<Singleton>()
                    expose<MyDatabase>()
                    bind<MyService>().to<MyServiceImpl>().`in`<Singleton>()
                    expose<MyService>()
                }
            }
    ))
    val myService = injector.getInstance<MyService>()
    val myDatabase = injector.getInstance<MyDatabase>()
    myService.doWork()
    myDatabase.doStuff()
```

> Exception in thread "main" com.google.inject.ConfigurationException: Guice configuration errors:                                                                                              
>                                                                                                                                                                                               
> 1) Unable to create binding for my.MyDatabase. It was already configured on one or more child injectors or private modules                                                                    
>     bound at my.MainKt$main$injector$2.configure(Main.kt:109) (via modules: com.google.inject.util.Modules$OverrideModule -> my.MainKt$main$injector$2)                                           bound at com.authzee.kotlinguice4.KotlinPrivateBinder.bind(KotlinPrivateBinder.kt) (via modules: com.google.inject.util.Modules$OverrideModule -> my.MainKt$main$injector$2)              
>   If it was in a PrivateModule, did you forget to expose the binding?                                                                                                                         
>   while locating my.MyDatabase                                                                                                                                                                
>                                                                                                                                                                                               
> 1 error                                                                                                                                                                                       
>     at com.google.inject.internal.InjectorImpl.getProvider(InjectorImpl.java:1045)                                                                                                            
>     at com.google.inject.internal.InjectorImpl.getInstance(InjectorImpl.java:1050)                                                                                                            
>     at my.MainKt.main(Main.kt:104)

**Comment by fusr** [comment]
Works in Java..
