### ISSUE TITLE
Logger goes haywire on binding not found

### ISSUE THREAD

**Issue by nsoft** [google/guice#1284]
After some hour or so of digging I found (via wandering through a debugger stack) that the stack trace below actually represents this error:

"No implementation for com.needhamsoftware.nslogin.service.ActionService was bound."

Hard to see how this wouldn't be a bug... Clearly that message should wind up in the stack trace (but it does not, see below)

When I manage check in (it's open source) I'll point you at the (fixed) version of the configuration, removing the binding for this service should reproduce...

Environment:
```
14-Dec-2019 00:38:19.513 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Server version:        Apache Tomcat/8.5.37
14-Dec-2019 00:38:19.515 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Server built:          Dec 12 2018 12:07:02 UTC
14-Dec-2019 00:38:19.515 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Server number:         8.5.37.0
14-Dec-2019 00:38:19.515 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log OS Name:               Linux
14-Dec-2019 00:38:19.515 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log OS Version:            4.15.0-70-generic
14-Dec-2019 00:38:19.516 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Architecture:          amd64
14-Dec-2019 00:38:19.516 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Java Home:             /usr/lib/jvm/java-11-openjdk-amd64
14-Dec-2019 00:38:19.516 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log JVM Version:           11.0.4+11-post-Ubuntu-1ubuntu218.04.3
14-Dec-2019 00:38:19.516 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log JVM Vendor:            Ubuntu
```

```
java.util.logging.ErrorManager: 5
com.google.common.util.concurrent.UncheckedExecutionException: java.lang.IllegalArgumentException
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2207)
	at com.google.common.cache.LocalCache.get(LocalCache.java:3953)
	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3957)
	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4875)
	at com.google.common.cache.LocalCache$LocalLoadingCache.getUnchecked(LocalCache.java:4881)
	at com.google.inject.internal.util.StackTraceElements.forMember(StackTraceElements.java:66)
	at com.google.inject.internal.Errors.formatInjectionPoint(Errors.java:831)
	at com.google.inject.internal.Errors.formatSource(Errors.java:800)
	at com.google.inject.internal.Errors.formatSource(Errors.java:785)
	at com.google.inject.internal.Errors.format(Errors.java:584)
	at com.google.inject.ConfigurationException.getMessage(ConfigurationException.java:72)
	at java.base/java.lang.Throwable.getLocalizedMessage(Throwable.java:396)
	at java.base/java.lang.Throwable.toString(Throwable.java:485)
	at java.base/java.lang.String.valueOf(String.java:2951)
	at java.base/java.io.PrintWriter.println(PrintWriter.java:837)
	at java.base/java.lang.Throwable$WrappedPrintWriter.println(Throwable.java:768)
	at java.base/java.lang.Throwable.printStackTrace(Throwable.java:659)
	at java.base/java.lang.Throwable.printStackTrace(Throwable.java:725)
	at org.apache.juli.OneLineFormatter.format(OneLineFormatter.java:159)
	at org.apache.juli.FileHandler.publish(FileHandler.java:290)
	at org.apache.juli.AsyncFileHandler.publishInternal(AsyncFileHandler.java:146)
	at org.apache.juli.AsyncFileHandler$LogEntry.flush(AsyncFileHandler.java:186)
	at org.apache.juli.AsyncFileHandler$LoggerThread.run(AsyncFileHandler.java:162)
Caused by: java.lang.IllegalArgumentException
	at com.google.inject.internal.asm.$ClassReader.<init>(Unknown Source)
	at com.google.inject.internal.asm.$ClassReader.<init>(Unknown Source)
	at com.google.inject.internal.asm.$ClassReader.<init>(Unknown Source)
	at com.google.inject.internal.util.LineNumbers.<init>(LineNumbers.java:65)
	at com.google.inject.internal.util.StackTraceElements$1.load(StackTraceElements.java:46)
	at com.google.inject.internal.util.StackTraceElements$1.load(StackTraceElements.java:43)
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3542)
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2323)
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2286)
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2201)
	... 22 more
```

**Comment by mcculls** [comment]
Hi, which version of Guice are you using?

This looks like a known issue where the version of ASM currently used by Guice can't read a class compiled with a later JDK (it's doing this to provide better line numbers.) Unfortunately the `StackTraceElements` code doesn't handle this situation robustly - ideally it would fall back to report what location information it has rather than propagating the ASM exception.

**Comment by GedMarc** [comment]
You can use the guice library re-package at https://search.maven.org/artifact/com.guicedee.services/guice/
for the newer JDK's

**Comment by GedMarc** [comment]
@mcculls oh also, byte buddy falls prey to the same error on jdk 13 for illegal access by the way, no point in adding it in.
Also as ASM is now bundled with the JDK (jdk.internal.asm) it is better to use it instead of going down that route.

**Comment by mcculls** [comment]
@GedMarc the class involved in this bug report `StackTraceElements` uses ASM directly. It is not related to the effort to replace CGLIB. It is certainly possible to make `StackTraceElements` fail in a more robust way which would future-proof against further unforeseen changes to bytecode.

Wrt. the CGLIB replacement work... that no longer depends on byte-buddy directly - and JDK 13 is one of my test environments along with early builds of JDK 14.

Finally the JDK team discourage people from depending on anything under `jdk.internal` because it's not guaranteed all JRE distributions will provide this. (It's also not exported by default which means you need extra JDK options to see it.)

**Comment by nsoft** [comment]
Using compile 'com.google.inject:guice:4.0'

**Comment by mcculls** [comment]
Could you try setting the `guice_include_stack_traces` system property to `OFF` to see if it helps?

**Comment by winfriedgerlach** [comment]
@nsoft @cushon @eamonnmcmanus since this issues concerns the outdated Guice version 4.0 and has been inactive for years, can this issue be closed?
