### ISSUE TITLE
No error log in tomcat after crash

### ISSUE THREAD

**Issue by SettingDust** [google/guice#1285]
```
20-Dec-2019 09:40:34.554 信息 [AsyncFileHandlerWriter-1596000437] org.apache.catalina.loader.WebappClassLoaderBase.checkStateForResourceLoading Illegal access: this web application instance has been stopped already.  Could not load [com.google.inject.internal.util.LineNumbers$LineNumberReader]。为了调试以及终止导致非法访问的线程，将抛出以下堆栈跟踪。
    java.lang.IllegalStateException: this web application instance has been stopped already.  Could not load [com.google.inject.internal.util.LineNumbers$LineNumberReader]。为了调试以及终止导致非法访问的线程，将抛出以下堆栈跟踪。
        at org.apache.catalina.loader.WebappClassLoaderBase.checkStateForResourceLoading(WebappClassLoaderBase.java:1385)
        at org.apache.catalina.loader.WebappClassLoaderBase.checkStateForClassLoading(WebappClassLoaderBase.java:1373)
        at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1226)
        at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1188)
        at com.google.inject.internal.util.StackTraceElements$1.load(StackTraceElements.java:49)
        at com.google.inject.internal.util.StackTraceElements$1.load(StackTraceElements.java:45)
        at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3529)
        at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2278)
        at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2155)
        at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2045)
        at com.google.common.cache.LocalCache.get(LocalCache.java:3953)
        at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3976)
        at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4960)
        at com.google.common.cache.LocalCache$LocalLoadingCache.getUnchecked(LocalCache.java:4966)
        at com.google.inject.internal.util.StackTraceElements.forMember(StackTraceElements.java:71)
        at com.google.inject.internal.Messages.formatSource(Messages.java:241)
        at com.google.inject.internal.Messages.formatSource(Messages.java:220)
        at com.google.inject.internal.Messages.formatInjectionPoint(Messages.java:276)
        at com.google.inject.internal.Messages.formatSource(Messages.java:235)
        at com.google.inject.internal.Messages.formatSource(Messages.java:220)
        at com.google.inject.internal.Messages.formatMessages(Messages.java:90)
        at com.google.inject.ProvisionException.getMessage(ProvisionException.java:61)
        at java.base/java.lang.Throwable.getLocalizedMessage(Throwable.java:396)
        at java.base/java.lang.Throwable.toString(Throwable.java:495)
        at java.base/java.lang.String.valueOf(String.java:3042)
        at java.base/java.io.PrintWriter.println(PrintWriter.java:837)
        at org.apache.juli.OneLineFormatter$IndentingPrintWriter.println(OneLineFormatter.java:250)
        at java.base/java.lang.Throwable$WrappedPrintWriter.println(Throwable.java:778)
        at java.base/java.lang.Throwable.printStackTrace(Throwable.java:669)
        at java.base/java.lang.Throwable.printStackTrace(Throwable.java:735)
        at org.apache.juli.OneLineFormatter.format(OneLineFormatter.java:150)
        at org.apache.juli.FileHandler.publish(FileHandler.java:294)
        at org.apache.juli.AsyncFileHandler.publishInternal(AsyncFileHandler.java:146)
        at org.apache.juli.AsyncFileHandler$LogEntry.flush(AsyncFileHandler.java:185)
        at org.apache.juli.AsyncFileHandler$LoggerThread.run(AsyncFileHandler.java:161)
```
```
private final UserService userService;  
  
@Inject  
public UserApiServlet(UserService userService) {  
    this.userService = userService;  
}
```
Problem is gone by remove these lines

It seems that the guice run a new thread to print the error after my webapp is shutdown.

**Comment by mcculls** [comment]
Hi, Guice does not create threads itself - from your stack trace this thread was created by Tomcat itself, specifically `org.apache.juli.AsyncFileHandler` which appears to be something to do with asynchronous logging.

As far as I can tell your application logs a message that involves Guice, and Tomcat then handles this log message asynchronously on a different thread. Unfortunately it only attempts to process this message during shutdown after the application classloader has been unloaded, and the classes needed to format the message are no longer available.

One solution would be to make sure that Tomcat flushed its log message queue before unloading the application classloader. Alternatively you could try setting the `guice_include_stack_traces` system property to `OFF` which should avoid the need to lookup the additional class to format the message.

**Comment by SettingDust** [comment]
> Hi, Guice does not create threads itself - from your stack trace this thread was created by Tomcat itself, specifically `org.apache.juli.AsyncFileHandler` which appears to be something to do with asynchronous logging.
> 
> As far as I can tell your application logs a message that involves Guice, and Tomcat then handles this log message asynchronously on a different thread. Unfortunately it only attempts to process this message during shutdown after the application classloader has been unloaded, and the classes needed to format the message are no longer available.
> 
> One solution would be to make sure that Tomcat flushed its log message queue before unloading the application classloader. Alternatively you could try setting the `guice_include_stack_traces` system property to `OFF` which should avoid the need to lookup the additional class to format the message.

At last, I use the debugger to pause the main thread and done

**Comment by Shubhamhack7** [comment]
> guice_include_stack_traces

where i have to set this property to OFF
