### ISSUE TITLE
Beta 5 - Attempts to inject on enums

### ISSUE THREAD

**Issue by GedMarc** [google/guice#1451]
In the instance that EL references an enumeration, guice beta 5 tries to create an instance of it :)

```
[2020/11/18 06:18:32]-[Error Rendering View[/ui/admin/logging/api_log_viewer.xhtml]com.google.inject.ConfigurationException: Guice configuration errors:

1) [Guice/MissingConstructor]: No injectable constructor for type Apps.

class Apps does not have a @Inject annotated constructor or a no-arg constructor.

Requested by:
1  : Apps.class(Apps.java:3)
     while locating Apps

Learn more:
  https://github.com/google/guice/wiki/MISSING_CONSTRUCTOR

1 error

======================
Full classname legend:
======================
Apps: "xxxxxxxxxxxxx.Apps"
========================
End of classname legend:
========================

	at com.google.guice@0.0.0_0-SNAPSHOT/com.google.inject.internal.InjectorImpl.getProvider(InjectorImpl.java:1126)
	at com.google.guice@0.0.0_0-SNAPSHOT/com.google.inject.internal.InjectorImpl.getInstance(InjectorImpl.java:1133)
	at com.guicedee.guicedinjection@0.0.0_0-SNAPSHOT/com.guicedee.guicedinjection.GuiceContext.get(GuiceContext.java:317)
	at com.guicedee.guicedinjection@0.0.0_0-SNAPSHOT/com.guicedee.guicedinjection.GuiceContext.get(GuiceContext.java:275)
	at com.guicedee.guicedinjection@0.0.0_0-SNAPSHOT/com.guicedee.guicedinjection.GuiceContext.get(GuiceContext.java:175)
	at jakarta.faces@0.0.0_0-SNAPSHOT/com.sun.faces.application.applicationimpl.InstanceFactory.newConverter(InstanceFactory.java:1059)
	at jakarta.faces@0.0.0_0-SNAPSHOT/com.sun.faces.application.applicationimpl.InstanceFactory.createConverterBasedOnClass(InstanceFactory.java:966)

```

```
public enum Apps
{
	//@formatter:off
	//@formatter:on
}
```

**Comment by winfriedgerlach** [comment]
@GedMarc @cushon @eamonnmcmanus since this issues seems to have been fixed in Guice 5.0.1, can this issue be closed?
