### ISSUE TITLE
NPE in generated code

### ISSUE THREAD

**Issue by zreed** [google/guice#1544]
I'm getting an NPE in generated code with Guice 5.0.1 on OpenJDK 17:

```
java.lang.NullPointerException: Cannot invoke "java.lang.Integer.intValue()" because the return value of "java.lang.reflect.InvocationHandler.invoke(Object, java.lang.reflect.Method, Object[])" is null`
        at net.zreed.providers.PopulateDatabaseWithCreatedPractitioners$$EnhancerByGuice$$88888058.hashCode(<generated>)
        at com.google.common.collect.ImmutableSet$RegularSetBuilderImpl.insertInHashTable(ImmutableSet.java:759)
        at com.google.common.collect.ImmutableSet$RegularSetBuilderImpl.add(ImmutableSet.java:754)
        at com.google.common.collect.ImmutableSet$RegularSetBuilderImpl.add(ImmutableSet.java:751)
        at com.google.common.collect.ImmutableSet.construct(ImmutableSet.java:205)
        at com.google.common.collect.ImmutableSet.constructUnknownDuplication(ImmutableSet.java:170)
        at com.google.common.collect.ImmutableSet.copyOf(ImmutableSet.java:298)
        at com.google.inject.internal.RealMultibinder$RealMultibinderProvider.doProvision(RealMultibinder.java:212)
        at com.google.inject.internal.RealMultibinder$RealMultibinderProvider.doProvision(RealMultibinder.java:159)
        at com.google.inject.internal.InternalProviderInstanceBindingImpl$Factory.get(InternalProviderInstanceBindingImpl.java:113)
        at com.google.inject.internal.InjectorImpl$1.get(InjectorImpl.java:1100)
        at com.google.inject.internal.InjectorImpl.getInstance(InjectorImpl.java:1133)
```

Adding an explicit `hashCode()` to `PopulateDatabaseWithCreatedPractitioners` doesn't seem to solve the issue (wasn't too confident it would but worth a try) and I don't know enough about Guice's inner workings to effectively find the issue.

**Comment by GedMarc** [comment]
have you got a reproducer?

**Comment by mcculls** [comment]
Hi @zreed at first glance it looks like there could be a method interceptor which is returning `null` when intercepting the `hashCode` method - and that's causing the NPE.

I'd suggest checking your configuration to see what method matchers and interceptors are being used.

As @GedMarc said a reproducible project/test or even some snippets of method interceptors used in the project would be helpful.

**Comment by zreed** [comment]
@mcculls you were spot on, after some digging I found an interceptor that was returning null for every call.
