### ISSUE TITLE
An error is reported when the Android system application uses Guice

### ISSUE THREAD

**Issue by by8023hxy** [google/guice#1574]
Hello, I'm an Android Developer，An error is reported when the Android system application uses Guice。

 44 errors
        at android.app.ActivityThread.installProvider(ActivityThread.java:6396)
        at android.app.ActivityThread.installContentProviders(ActivityThread.java:5938)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5853)
        at android.app.ActivityThread.access$1100(ActivityThread.java:199)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1650)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
     Caused by: com.google.inject.CreationException: Guice creation errors:
    
    1) No implementation for java.lang.Boolean annotated with @com.google.inject.name.Named(value=joynr.accesscontrol.enable) was bound.
      while locating java.lang.Boolean annotated with @com.google.inject.name.Named(value=joynr.accesscontrol.enable)
        for parameter 9 at io.joynr.messaging.routing.CcMessageRouter.<init>(Unknown Source)
        at io.joynr.runtime.ClusterControllerRuntimeModule.configure(ClusterControllerRuntimeModule.java:61)
    
    2) No implementation for java.lang.Boolean annotated with @com.google.inject.name.Named(value=joynr.messaging.backpressure.enabled) was bound.
      while locating java.lang.Boolean annotated with @com.google.inject.name.Named(value=joynr.messaging.backpressure.enabled)
        for parameter 4 at io.joynr.messaging.mqtt.MqttMessagingSkeletonProvider.<init>(Unknown Source)
        at io.joynr.messaging.mqtt.MqttModule.configure(MqttModule.java:144)
    
    3) No implementation for java.lang.Boolean annotated with @com.google.inject.name.Named(value=joynr.messaging.compressreplies) was bound.
      while locating java.lang.Boolean annotated with @com.google.inject.name.Named(value=joynr.messaging.compressreplies)
        for parameter 6 at io.joynr.dispatching.DispatcherImpl.<init>(Unknown Source)
        at io.joynr.runtime.AbstractRuntimeModule.configure(AbstractRuntimeModule.java:137)
    
    4) No implementation for java.lang.Boolean annotated with @com.google.inject.name.Named(value=joynr.messaging.mqtt.cleansession) was bound.
      while locating java.lang.Boolean annotated with @com.google.inject.name.Named(value=joynr.messaging.mqtt.cleansession)
2022-01-27 10:04:04.226 2548-2548/com.gwm.sota E/AndroidRuntime:     for parameter 4 at io.joynr.messaging.mqtt.hivemq.client.HivemqMqttClientFactory.<init>(Unknown Source)
        at io.joynr.messaging.mqtt.hivemq.client.HivemqMqttClientModule.configure(HivemqMqttClientModule.java:34)
    
    5) No implementation for java.lang.Boolean annotated with @com.google.inject.name.Named(value=joynr.messaging.mqtt.enable.sharedsubscriptions) was bound.
      while locating java.lang.Boolean annotated with @com.google.inject.name.Named(value=joynr.messaging.mqtt.enable.sharedsubscriptions)
        for parameter 1 at io.joynr.messaging.mqtt.MqttMessagingSkeletonProvider.<init>(Unknown Source)
        at io.joynr.messaging.mqtt.MqttModule.configure(MqttModule.java:144)
    
    6) No implementation for java.lang.Boolean annotated with @com.google.inject.name.Named(value=joynr.messaging.mqtt.separateconnections) was bound.
      while locating java.lang.Boolean annotated with @com.google.inject.name.Named(value=joynr.messaging.mqtt.separateconnections)
        for parameter 0 at io.joynr.messaging.mqtt.hivemq.client.HivemqMqttClientFactory.<init>(Unknown Source)
        at io.joynr.messaging.mqtt.hivemq.client.HivemqMqttClientModule.configure(HivemqMqttClientModule.java:34)
    
    7) No implementation for java.lang.Integer annotated with @com.google.inject.name.Named(value=joynr.cc.discovery.entry.cache.cleanup.interval) was bound.
      while locating java.lang.Integer annotated with @com.google.inject.name.Named(value=joynr.cc.discovery.entry.cache.cleanup.interval)
        for parameter 1 at io.joynr.capabilities.ExpiredDiscoveryEntryCacheCleaner.<init>(Unknown Source)
      while locating io.joynr.capabilities.ExpiredDiscoveryEntryCacheCleaner
        for parameter 6 at io.joynr.capabilities.LocalCapabilitiesDirectoryImpl.<init>(Unknown Source)
        at io.joynr.capabilities.LocalCapabilitiesDirectoryModule.configure(LocalCapabilitiesDirectoryModule.java:41)
    
    8) No implementation for java.lang.Integer annotated with @com.google.inject.name.Named(value=joynr.messaging.backpressure.incomingmqttrequests.lowerthreshold) was bound.
      while locating java.lang.Integer annotated with @com.google.inject.name.Named(value=joynr.messaging.backpressure.incomingmqttrequests.lowerthreshold)
        for parameter 6 at io.joynr.messaging.mqtt.MqttMessagingSkeletonProvider.<init>(Unknown Source)
        at io.joynr.messaging.mqtt.MqttModule.configure(MqttModule.java:144)
    
    9) No implementation for java.lang.Integer annotated with @com.google.inject.name.Named(value=joynr.messaging.backpressure.incomingmqttrequests.upperthreshold) was bound.
      while locating java.lang.Integer annotated with @com.google.inject.name.Named(value=joynr.messaging.backpressure.incomingmqttrequests.upperthreshold)
        for parameter 5 at io.joynr.messaging.mqtt.MqttMessagingSkeletonProvider.<init>(Unknown Source)
        at io.joynr.messaging.mqtt.MqttModule.configure(MqttModule.java:144)
    
    10) No implementation for java.lang.Integer annotated with @com.google.inject.name.Named(value=joynr.messaging.maximumparallelsends) was bound.
      while locating java.lang.Integer annotated with @com.google.inject.name.Named(value=joynr.messaging.maximumparallelsends)
        for parameter 1 at io.joynr.messaging.ConfigurableMessagingSettings.<init>(Unknown Source)
        at io.joynr.runtime.AbstractRuntimeModule.configure(AbstractRuntimeModule.java:142)
    
    11) No implementation for java.lang.Integer annotated with @com.google.inject.name.Named(value=joynr.messaging.maximumparallelsends) was bound.
      while locating java.lang.Integer annotated with @com.google.inject.name.Named(value=joynr.messaging.maximumparallelsends)
        for parameter 2 at io.joynr.messaging.routing.CcMessageRouter.<init>(Unknown Source)
        at io.joynr.runtime.ClusterControllerRuntimeModule.configure(ClusterControllerRuntimeModule.java:61)
    
    12) No implementation for java.lang.Integer annotated with @com.google.inject.name.Named(value=joynr.messaging.maximumparallelsends) was bound.
      while locating java.lang.Integer annotated with @com.google.inject.name.Named(value=joynr.messaging.maximumparallelsends)
2022-01-27 10:04:04.227 2548-2548/com.gwm.sota E/AndroidRuntime:     for parameter 0 at io.joynr.runtime.DefaultScheduledExecutorServiceProvider.<init>(Unknown Source)
        at io.joynr.runtime.AbstractRuntimeModule.configure(AbstractRuntimeModule.java:145)
    
    13) No implementation for java.lang.Integer annotated with @com.google.inject.name.Named(value=joynr.messaging.maximumparallelsends) was bound.
      while locating java.lang.Integer annotated with @com.google.inject.name.Named(value=joynr.messaging.maximumparallelsends)
        for parameter 0 at io.joynr.runtime.DefaultScheduledExecutorServiceProvider.<init>(Unknown Source)
        at io.joynr.runtime.AbstractRuntimeModule.configure(AbstractRuntimeModule.java:156)
    
    14) No implementation for java.lang.Integer annotated with @com.google.inject.name.Named(value=joynr.messaging.maximumparallelsends) was bound.
      while locating java.lang.Integer annotated with @com.google.inject.name.Named(value=joynr.messaging.maximumparallelsends)
        for parameter 0 at io.joynr.runtime.DefaultScheduledExecutorServiceProvider.<init>(Unknown Source)
        at io.joynr.runtime.ClusterControllerRuntimeModule.configure(ClusterControllerRuntimeModule.java:68)
    
    15) No implementation for java.lang.Integer annotated with @com.google.inject.name.Named(value=joynr.messaging.maxincomingmqttrequests) was bound.
      while locating java.lang.Integer annotated with @com.google.inject.name.Named(value=joynr.messaging.maxincomingmqttrequests)
        for parameter 3 at io.joynr.messaging.mqtt.MqttMessagingSkeletonProvider.<init>(Unknown Source)
        at io.joynr.messaging.mqtt.MqttModule.configure(MqttModule.java:144)
    
    16) No implementation for java.lang.Long annotated with @com.google.inject.name.Named(value=joynr.capabilities.freshnessupdateintervalms) was bound.
      while locating java.lang.Long annotated with @com.google.inject.name.Named(value=joynr.capabilities.freshnessupdateintervalms)
        for parameter 7 at io.joynr.capabilities.LocalCapabilitiesDirectoryImpl.<init>(Unknown Source)
        at io.joynr.capabilities.LocalCapabilitiesDirectoryModule.configure(LocalCapabilitiesDirectoryModule.java:41)
    
    17) No implementation for java.lang.Long annotated with @com.google.inject.name.Named(value=joynr.discovery.defaultretryintervalms) was bound.
      while locating java.lang.Long annotated with @com.google.inject.name.Named(value=joynr.discovery.defaultretryintervalms)
        for parameter 5 at io.joynr.proxy.DiscoverySettingsStorage.<init>(Unknown Source)
      while locating io.joynr.proxy.DiscoverySettingsStorage
        for parameter 7 at io.joynr.runtime.ClusterControllerRuntime.<init>(Unknown Source)
        at io.joynr.runtime.CCInProcessRuntimeModule.configure(CCInProcessRuntimeModule.java:37)
    
    18) No implementation for java.lang.Long annotated with @com.google.inject.name.Named(value=joynr.discovery.defaultretryintervalms) was bound.
      while locating java.lang.Long annotated with @com.google.inject.name.Named(value=joynr.discovery.defaultretryintervalms)
        for parameter 6 at io.joynr.proxy.ProxyBuilderFactoryImpl.<init>(Unknown Source)
        at io.joynr.runtime.AbstractRuntimeModule.configure(AbstractRuntimeModule.java:133)
    
    19) No implementation for java.lang.Long annotated with @com.google.inject.name.Named(value=joynr.discovery.defaulttimeoutms) was bound.
      while locating java.lang.Long annotated with @com.google.inject.name.Named(value=joynr.discovery.defaulttimeoutms)
        for parameter 4 at io.joynr.proxy.DiscoverySettingsStorage.<init>(Unknown Source)
      while locating io.joynr.proxy.DiscoverySettingsStorage
        for parameter 7 at io.joynr.runtime.ClusterControllerRuntime.<init>(Unknown Source)
        at io.joynr.runtime.CCInProcessRuntimeModule.configure(CCInProcessRuntimeModule.java:37)
    
    20) No implementation for java.lang.Long annotated with @com.google.inject.name.Named(value=joynr.discovery.defaulttimeoutms) was bound.
      while locating java.lang.Long annotated with @com.google.inject.name.Named(value=joynr.discovery.defaulttimeoutms)
        for parameter 5 at io.joynr.proxy.ProxyBuilderFactoryImpl.<init>(Unknown Source)
2022-01-27 10:04:04.227 2548-2548/com.gwm.sota E/AndroidRuntime:     at io.joynr.runtime.AbstractRuntimeModule.configure(AbstractRuntimeModule.java:133)
    
    21) No implementation for java.lang.Long annotated with @com.google.inject.name.Named(value=joynr.discovery.minimumretryintervalms) was bound.
      while locating java.lang.Long annotated with @com.google.inject.name.Named(value=joynr.discovery.minimumretryintervalms)
        for parameter 7 at io.joynr.proxy.ProxyBuilderFactoryImpl.<init>(Unknown Source)
        at io.joynr.runtime.AbstractRuntimeModule.configure(AbstractRuntimeModule.java:133)
    
    22) No implementation for java.lang.Long annotated with @com.google.inject.name.Named(value=joynr.discovery.provider.defaultexpirytimems) was bound.
      while locating java.lang.Long annotated with @com.google.inject.name.Named(value=joynr.discovery.provider.defaultexpirytimems)
        for parameter 5 at io.joynr.capabilities.CapabilitiesRegistrarImpl.<init>(Unknown Source)
        at io.joynr.runtime.AbstractRuntimeModule.configure(AbstractRuntimeModule.java:140)
    
    23) No implementation for java.lang.Long annotated with @com.google.inject.name.Named(value=joynr.discovery.provider.defaultexpirytimems) was bound.
      while locating java.lang.Long annotated with @com.google.inject.name.Named(value=joynr.discovery.provider.defaultexpirytimems)
        for parameter 11 at io.joynr.capabilities.LocalCapabilitiesDirectoryImpl.<init>(Unknown Source)
        at io.joynr.capabilities.LocalCapabilitiesDirectoryModule.configure(LocalCapabilitiesDirectoryModule.java:41)
    
    24) No implementation for java.lang.Long annotated with @com.google.inject.name.Named(value=joynr.messaging.maxttlms) was bound.
      while locating java.lang.Long annotated with @com.google.inject.name.Named(value=joynr.messaging.maxttlms)
        for parameter 3 at io.joynr.proxy.DiscoverySettingsStorage.<init>(Unknown Source)
      while locating io.joynr.proxy.DiscoverySettingsStorage
        for parameter 7 at io.joynr.runtime.ClusterControllerRuntime.<init>(Unknown Source)
        at io.joynr.runtime.CCInProcessRuntimeModule.configure(CCInProcessRuntimeModule.java:37)
    
    25) No implementation for java.lang.Long annotated with @com.google.inject.name.Named(value=joynr.messaging.maxttlms) was bound.
      while locating java.lang.Long annotated with @com.google.inject.name.Named(value=joynr.messaging.maxttlms)
        for parameter 4 at io.joynr.proxy.ProxyBuilderFactoryImpl.<init>(Unknown Source)
        at io.joynr.runtime.AbstractRuntimeModule.configure(AbstractRuntimeModule.java:133)
    
    26) No implementation for java.lang.Long annotated with @com.google.inject.name.Named(value=joynr.messaging.removestaledelayms) was bound.
      while locating java.lang.Long annotated with @com.google.inject.name.Named(value=joynr.messaging.removestaledelayms)
        for parameter 17 at io.joynr.runtime.ClusterControllerRuntime.<init>(Unknown Source)
        at io.joynr.runtime.CCInProcessRuntimeModule.configure(CCInProcessRuntimeModule.java:37)
    
    27) No implementation for java.lang.Long annotated with @com.google.inject.name.Named(value=joynr.messaging.routingtablecleanupintervalms) was bound.
      while locating java.lang.Long annotated with @com.google.inject.name.Named(value=joynr.messaging.routingtablecleanupintervalms)
        for parameter 3 at io.joynr.messaging.routing.CcMessageRouter.<init>(Unknown Source)
        at io.joynr.runtime.ClusterControllerRuntimeModule.configure(ClusterControllerRuntimeModule.java:61)
    
    28) No implementation for java.lang.Long annotated with @com.google.inject.name.Named(value=joynr.messaging.routingtablegraceperiodms) was bound.
      while locating java.lang.Long annotated with @com.google.inject.name.Named(value=joynr.messaging.routingtablegraceperiodms)
        for parameter 0 at io.joynr.messaging.routing.RoutingTableImpl.<init>(Unknown Source)
        at io.joynr.runtime.ClusterControllerRuntimeModule.configure(ClusterControllerRuntimeModule.java:65)
    
    29) No implementation for java.lang.Long annotated with @com.google.inject.name.Named(value=joynr.messaging.sendmsgretryintervalms) was bound.
2022-01-27 10:04:04.227 2548-2548/com.gwm.sota E/AndroidRuntime:   while locating java.lang.Long annotated with @com.google.inject.name.Named(value=joynr.messaging.sendmsgretryintervalms)
        for parameter 0 at io.joynr.messaging.ConfigurableMessagingSettings.<init>(Unknown Source)
        at io.joynr.runtime.AbstractRuntimeModule.configure(AbstractRuntimeModule.java:142)
    
    30) No implementation for java.lang.String annotated with @com.google.inject.name.Named(value=joynr.capabilities.provisioned.file) was bound.
      while locating java.lang.String annotated with @com.google.inject.name.Named(value=joynr.capabilities.provisioned.file)
        for parameter 0 at io.joynr.capabilities.StaticCapabilitiesProvisioningWithRoutingTableInsertion.<init>(Unknown Source)
        at io.joynr.capabilities.StaticCapabilitiesProvisioningModule.configure(StaticCapabilitiesProvisioningModule.java:31)
    
    31) No implementation for java.lang.String annotated with @com.google.inject.name.Named(value=joynr.messaging.discoveryproviderparticipantid) was bound.
      while locating java.lang.String annotated with @com.google.inject.name.Named(value=joynr.messaging.discoveryproviderparticipantid)
        for parameter 3 at io.joynr.accesscontrol.AccessControllerImpl.<init>(Unknown Source)
        at io.joynr.accesscontrol.AccessControlClientModule.configure(AccessControlClientModule.java:31)
    
    32) No implementation for java.lang.String annotated with @com.google.inject.name.Named(value=joynr.messaging.discoveryproviderparticipantid) was bound.
      while locating java.lang.String annotated with @com.google.inject.name.Named(value=joynr.messaging.discoveryproviderparticipantid)
        for parameter 2 at io.joynr.capabilities.PropertiesFileParticipantIdStorage.<init>(Unknown Source)
        at io.joynr.runtime.AbstractRuntimeModule.configure(AbstractRuntimeModule.java:141)
    
    33) No implementation for java.lang.String annotated with @com.google.inject.name.Named(value=joynr.messaging.discoveryproviderparticipantid) was bound.
      while locating java.lang.String annotated with @com.google.inject.name.Named(value=joynr.messaging.discoveryproviderparticipantid)
        for parameter 1 at io.joynr.discovery.LocalDiscoveryAggregator.<init>(Unknown Source)
        at io.joynr.runtime.AbstractRuntimeModule.configure(AbstractRuntimeModule.java:138)
    
    34) No implementation for java.lang.String annotated with @com.google.inject.name.Named(value=joynr.messaging.mqtt.enable.sharedsubscriptions) was bound.
      while locating java.lang.String annotated with @com.google.inject.name.Named(value=joynr.messaging.mqtt.enable.sharedsubscriptions)
        for parameter 3 at io.joynr.messaging.mqtt.MqttReplyToAddressFactory.<init>(Unknown Source)
        at io.joynr.messaging.mqtt.MqttModule.configure(MqttModule.java:158)
    
    35) No implementation for java.lang.String annotated with @com.google.inject.name.Named(value=joynr.messaging.mqtt.enable.sharedsubscriptions) was bound.
      while locating java.lang.String annotated with @com.google.inject.name.Named(value=joynr.messaging.mqtt.enable.sharedsubscriptions)
        for parameter 3 at io.joynr.messaging.mqtt.MqttReplyToAddressFactory.<init>(Unknown Source)
        at io.joynr.messaging.mqtt.MqttModule.provideMqttOwnAddress(Unknown Source)
    
    36) No implementation for java.lang.String annotated with @com.google.inject.name.Named(value=joynr.messaging.mqtt.ssl.ciphersuites) was bound.
      while locating java.lang.String annotated with @com.google.inject.name.Named(value=joynr.messaging.mqtt.ssl.ciphersuites)
        for parameter 0 at io.joynr.messaging.mqtt.MqttCiphersuiteListFactory.<init>(Unknown Source)
        at io.joynr.messaging.mqtt.MqttModule.provideMqttInternalCipherList(Unknown Source)
    
    37) No implementation for java.lang.String annotated with @com.google.inject.name.Named(value=joynr.messaging.mqtt.topicprefix.multicast) was bound.
      while locating java.lang.String annotated with @com.google.inject.name.Named(value=joynr.messaging.mqtt.topicprefix.multicast)
        for parameter 2 at io.joynr.messaging.mqtt.DefaultMqttTopicPrefixProvider.<init>(Unknown Source)
2022-01-27 10:04:04.227 2548-2548/com.gwm.sota E/AndroidRuntime:     at io.joynr.messaging.mqtt.MqttModule.configure(MqttModule.java:166)
    
    38) No implementation for java.lang.String annotated with @com.google.inject.name.Named(value=joynr.messaging.mqtt.topicprefix.sharedsubscriptionsreplyto) was bound.
      while locating java.lang.String annotated with @com.google.inject.name.Named(value=joynr.messaging.mqtt.topicprefix.sharedsubscriptionsreplyto)
        for parameter 0 at io.joynr.messaging.mqtt.DefaultMqttTopicPrefixProvider.<init>(Unknown Source)
        at io.joynr.messaging.mqtt.MqttModule.configure(MqttModule.java:166)
    
    39) No implementation for java.lang.String annotated with @com.google.inject.name.Named(value=joynr.messaging.mqtt.topicprefix.unicast) was bound.
      while locating java.lang.String annotated with @com.google.inject.name.Named(value=joynr.messaging.mqtt.topicprefix.unicast)
        for parameter 1 at io.joynr.messaging.mqtt.DefaultMqttTopicPrefixProvider.<init>(Unknown Source)
        at io.joynr.messaging.mqtt.MqttModule.configure(MqttModule.java:166)
    
    40) No implementation for java.lang.String annotated with @com.google.inject.name.Named(value=joynr.messaging.routingproviderparticipantid) was bound.
      while locating java.lang.String annotated with @com.google.inject.name.Named(value=joynr.messaging.routingproviderparticipantid)
        for parameter 4 at io.joynr.accesscontrol.AccessControllerImpl.<init>(Unknown Source)
        at io.joynr.accesscontrol.AccessControlClientModule.configure(AccessControlClientModule.java:31)
    
    41) No implementation for java.lang.String annotated with @com.google.inject.name.Named(value=joynr.messaging.routingproviderparticipantid) was bound.
      while locating java.lang.String annotated with @com.google.inject.name.Named(value=joynr.messaging.routingproviderparticipantid)
        for parameter 3 at io.joynr.capabilities.PropertiesFileParticipantIdStorage.<init>(Unknown Source)
        at io.joynr.runtime.AbstractRuntimeModule.configure(AbstractRuntimeModule.java:141)
    
    42) No implementation for java.lang.String annotated with @com.google.inject.name.Named(value=joynr.messaging.routingproviderparticipantid) was bound.
      while locating java.lang.String annotated with @com.google.inject.name.Named(value=joynr.messaging.routingproviderparticipantid)
        for parameter 2 at io.joynr.discovery.LocalDiscoveryAggregator.<init>(Unknown Source)
        at io.joynr.runtime.AbstractRuntimeModule.configure(AbstractRuntimeModule.java:138)
    
    43) No implementation for java.lang.Long annotated with @com.google.inject.name.Named(value=joynr.capabilities.freshnessupdateintervalms) was bound.
      while locating java.lang.Long annotated with @com.google.inject.name.Named(value=joynr.capabilities.freshnessupdateintervalms)
        for field at io.joynr.capabilities.GlobalCapabilitiesDirectoryClient.freshnessUpdateIntervalMs(Unknown Source)
      while locating io.joynr.capabilities.GlobalCapabilitiesDirectoryClient
        for parameter 5 at io.joynr.capabilities.LocalCapabilitiesDirectoryImpl.<init>(Unknown Source)
        at io.joynr.capabilities.LocalCapabilitiesDirectoryModule.configure(LocalCapabilitiesDirectoryModule.java:41)
    
    44) No implementation for java.lang.Long annotated with @com.google.inject.name.Named(value=joynr.messaging.sendmsgretryintervalms) was bound.
      while locating java.lang.Long annotated with @com.google.inject.name.Named(value=joynr.messaging.sendmsgretryintervalms)
        for field at io.joynr.messaging.routing.MessageRouterUtil.sendMsgRetryIntervalMs(Unknown Source)
        at io.joynr.runtime.AbstractRuntimeModule.configure(AbstractRuntimeModule.java:101)

**Comment by winfriedgerlach** [comment]
@by8023hxy @cushon @eamonnmcmanus since this issues concerns the outdated Guice version 3.0 and has been inactive for years, can this issue be closed?
