### ISSUE TITLE
Spark2.4.7,Guice:4.0: java.lang.ArrayIndexOutOfBoundsException: 67737

### ISSUE THREAD

**Issue by liuzhuo19940206** [google/guice#1660]
com.google.inject.internal.util.$ComputationException: java.lang.ArrayIndexOutOfBoundsException: 67737
	at com.google.inject.internal.util.$MapMaker$StrategyImpl.compute(MapMaker.java:553)
	at com.google.inject.internal.util.$MapMaker$StrategyImpl.compute(MapMaker.java:419)
	at com.google.inject.internal.util.$CustomConcurrentHashMap$ComputingImpl.get(CustomConcurrentHashMap.java:2041)
	at com.google.inject.internal.util.$StackTraceElements.forMember(StackTraceElements.java:53)
	at com.google.inject.internal.Errors.formatSource(Errors.java:690)
	at com.google.inject.internal.Errors.formatInjectionPoint(Errors.java:720)
	at com.google.inject.internal.Errors.formatSource(Errors.java:684)
	at com.google.inject.internal.Errors.format(Errors.java:555)
	at com.google.inject.ProvisionException.getMessage(ProvisionException.java:59)
	at java.lang.Throwable.getLocalizedMessage(Throwable.java:392)
	at java.lang.Throwable.toString(Throwable.java:481)
	at java.lang.String.valueOf(String.java:2994)
	at java.io.PrintStream.println(PrintStream.java:821)
	at java.lang.Throwable$WrappedPrintStream.println(Throwable.java:749)
	at java.lang.Throwable.printStackTrace(Throwable.java:656)
	at java.lang.Throwable.printStackTrace(Throwable.java:644)
	at java.lang.Throwable.printStackTrace(Throwable.java:635)
	at com.jd.rec.nl.runtime.fullattrspark.FullAttrSparkProduce4.lambda$main$cc225c98$1(FullAttrSparkProduce4.java:272)
	at org.apache.spark.api.java.JavaRDDLike.$anonfun$foreachPartitionAsync$1(JavaRDDLike.scala:741)
	at org.apache.spark.api.java.JavaRDDLike.$anonfun$foreachPartitionAsync$1$adapted(JavaRDDLike.scala:741)
	at org.apache.spark.SparkContext.$anonfun$submitJob$1(SparkContext.scala:2416)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:90)
	at org.apache.spark.scheduler.Task.run(Task.scala:129)
	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$3(Executor.scala:478)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1480)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:481)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ArrayIndexOutOfBoundsException: 67737
	at com.google.inject.internal.asm.$ClassReader.<init>(Unknown Source)
	at com.google.inject.internal.asm.$ClassReader.<init>(Unknown Source)
	at com.google.inject.internal.asm.$ClassReader.<init>(Unknown Source)
	at com.google.inject.internal.util.$LineNumbers.<init>(LineNumbers.java:62)
	at com.google.inject.internal.util.$StackTraceElements$1.apply(StackTraceElements.java:36)
	at com.google.inject.internal.util.$StackTraceElements$1.apply(StackTraceElements.java:33)
	at com.google.inject.internal.util.$MapMaker$StrategyImpl.compute(MapMaker.java:549)
	... 28 more

**Comment by winfriedgerlach** [comment]
@liuzhuo19940206 @cushon @eamonnmcmanus since this issues concerns an outdated Guice version (judging by the title) and is inactive since years, can this issue be closed?
