### ISSUE TITLE
If the dependencies are managed up to Guava 18, there is a problem with Guice using a deprecated and no longer public method.

### ISSUE THREAD

**Issue by cgoudie** [google/guice#846]
java.lang.IllegalAccessError: tried to access method com.google.common.collect.MapMaker.makeComputingMap(Lcom/google/common/base/Function;)Ljava/util/concurrent/ConcurrentMap; from class com.google.inject.internal.Annotations$AnnotationChecker
    at com.google.inject.internal.Annotations$AnnotationChecker.<init>(Annotations.java:104)
    at com.google.inject.internal.Annotations.<clinit>(Annotations.java:122)
    at com.google.inject.spi.InjectionPoint.<init>(InjectionPoint.java:94)
    at com.google.inject.spi.InjectionPoint$InjectableField.toInjectionPoint(InjectionPoint.java:440)
    at com.google.inject.spi.InjectionPoint.getInjectionPoints(InjectionPoint.java:725)
    at com.google.inject.spi.InjectionPoint.forInstanceMethodsAndFields(InjectionPoint.java:358)
    at com.google.inject.spi.InjectionPoint.forInstanceMethodsAndFields(InjectionPoint.java:377)
    at com.google.inject.internal.BindingBuilder.toInstance(BindingBuilder.java:84)

I see that in the released version of the 4.0 beta: https://github.com/google/guice/blob/359c5c3ec4083dea3dd5060ffc4087d73ff98777/core/src/com/google/inject/internal/Annotations.java

On line 73 and 221 makeComputingMap is used. It's been changed to package scope in guava 18 it would appear.

**Comment by SobiborTreblinka** [comment]
I'm still getting this error in when running 4.0-beta5

**Comment by sameb** [comment]
Are you sure you don't have an earlier guice in your classpath somewhere?
