### ISSUE TITLE
Guice 4.0 + Info.Cukes 1.2.4 + ChromeDriver : Guice configuration errors

### ISSUE THREAD

**Issue by tinytongolai** [google/guice#994]
Guice Configuration:

`webDriver = new ChromeDriver();`

Error Log

`com.google.inject.ConfigurationException: Guice configuration errors:

1) No implementation for org.openqa.selenium.WebDriver was bound.
  while locating org.openqa.selenium.WebDriver
    for parameter 0 at PageStepDef.<init>(RegisterPageStepDef.java:40)
  while locating PageStepDef

1 error

	at com.google.inject.internal.InjectorImpl.getProvider(InjectorImpl.java:1042)
	at com.google.inject.internal.InjectorImpl.getProvider(InjectorImpl.java:1001)
	at com.google.inject.internal.InjectorImpl.getInstance(InjectorImpl.java:1051)
	at cucumber.runtime.java.guice.impl.GuiceFactory.getInstance(GuiceFactory.java:42)
	at cucumber.runtime.java.JavaStepDefinition.execute(JavaStepDefinition.java:38)
	at cucumber.runtime.StepDefinitionMatch.runStep(StepDefinitionMatch.java:37)
	at cucumber.runtime.Runtime.runStep(Runtime.java:299)
	at cucumber.runtime.model.StepContainer.runStep(StepContainer.java:44)
	at cucumber.runtime.model.StepContainer.runSteps(StepContainer.java:39)
	at cucumber.runtime.model.CucumberScenario.runBackground(CucumberScenario.java:59)
	at cucumber.runtime.model.CucumberScenario.run(CucumberScenario.java:42)
	at cucumber.runtime.junit.ExecutionUnitRunner.run(ExecutionUnitRunner.java:91)
	at cucumber.runtime.junit.FeatureRunner.runChild(FeatureRunner.java:63)
	at cucumber.runtime.junit.FeatureRunner.runChild(FeatureRunner.java:18)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at cucumber.runtime.junit.FeatureRunner.run(FeatureRunner.java:70)
	at cucumber.api.junit.Cucumber.runChild(Cucumber.java:93)
	at cucumber.api.junit.Cucumber.runChild(Cucumber.java:37)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at cucumber.api.junit.Cucumber.run(Cucumber.java:98)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:69)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:234)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:74)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)
`

**Comment by sameb** [comment]
This is an issue with your configuration, not with Guice.  I suggest asking on StackOverflow, or at the other libraries you mentioned.

**Comment by tinytongolai** [comment]
Guice 4.0 + Info.Cukes 1.1.1 + ChromeDriver => it works.
So why it's not working with Info.Cukes 1.2.4 .... ?

**Comment by sameb** [comment]
I have no idea what Info.Cukes is, but I suggest asking there.  The resolution is correct: the problem has nothing to do with Guice.

**Comment by sameb** [comment]
I should clarify -- obviously the problem has something to do with Guice based on the error message. However, there's nothing at fault in the core library here. This is a configuration error on the user side, and your best hope at support is asking the folks who configured it.

**Comment by tinytongolai** [comment]
for your information : https://cucumber.io/docs/reference/jvm

**Comment by ankoehn** [comment]
please check the changes of the info.cukes ver. 1.2.4:

[https://github.com/cucumber/cucumber-jvm/blob/master/History.md
](https://github.com/cucumber/cucumber-jvm/blob/master/History.md)

> [Guice] The cucumber-guice.properties file is no longer used. Use cucumber.properties instead.
