### ISSUE TITLE
GraphvizGrapher does not support optional bindings.  Fails with error even though Guice application works

### ISSUE THREAD

**Issue by jhauser8003** [google/guice#998]
Using the GraphvizGrapher to graph a working application.  However, the grapher gives the following exception when it cannot find a binding for an optional binding.

1) testMakeGrowGraph(com.google.corp.talent.common.guicegrapher.GuiceGrapherTest)com.google.inject.ConfigurationException: Guice configuration errors:

1) No implementation for com.google.template.soy.msgs.SoyMsgPlugin was bound.
  while locating com.google.template.soy.msgs.SoyMsgPlugin
    for parameter 0 at com.google.template.soy.msgs.SoyMsgBundleHandler.<init>(SoyMsgBundleHandler.java:108)
  while locating com.google.inject.Provider<com.google.template.soy.msgs.SoyMsgBundleHandler>

1 error
	at com.google.inject.internal.InjectorImpl.getBinding(InjectorImpl.java:160)
	at com.google.inject.internal.InjectorImpl.getBinding(InjectorImpl.java:68)
	at com.google.inject.grapher.AbstractInjectorGrapher.getBindings(AbstractInjectorGrapher.java:220)
	at com.google.inject.grapher.AbstractInjectorGrapher.graph(AbstractInjectorGrapher.java:108)
	at com.google.inject.grapher.AbstractInjectorGrapher.graph(AbstractInjectorGrapher.java:102)
	at com.google.corp.talent.common.guicegrapher.GuiceGrapher.getStringGraph(GuiceGrapher.java:87)

**Comment by tavianator** [comment]
Are you talking about `@Inject(optional = true)` or `OptionalBinder`?

**Comment by jhauser8003** [comment]
I believe I'm talking about OptionalBinder.

If you have code that works, and then you install the SoyModule, the code still works.
e.g.
`install(new SoyModule());`

However, the Guice Grapher starts to fail with the above error.  The dependency path that leads from  SoyModule to SoyMsgBundleHandler seems to be at SoyModule.java:145
`newOptionalBinder(binder(), Key.get(SoyMsgBundle.class, ForRequestLocale.class));`
and there are many more optional bindings:
`newOptionalBinder(binder(), SoyMsgBundleLoader.class);
      newOptionalBinder(binder(), SoyIdRenamingMap.class);
      newOptionalBinder(binder(), SoyCssRenamingMap.class);
      newOptionalBinder(binder(), new Key<Set<String>>(ActiveMods.class) {});`

the implemenation of newOptionalBinder is:

`  public static <T> OptionalBinder<T> newOptionalBinder(Binder binder, Key<T> type) {
    return newRealOptionalBinder(binder, type);
  }
  
  static <T> RealOptionalBinder<T> newRealOptionalBinder(Binder binder, Key<T> type) {
    binder = binder.skipSources(OptionalBinder.class, RealOptionalBinder.class);
    RealOptionalBinder<T> optionalBinder = new RealOptionalBinder<T>(binder, type);
    binder.install(optionalBinder);
    return optionalBinder;
  }`
